// identifier rules
// it cannot be a keyword
// should not start wth number or any special char except _
// cannot contain any special chars other than _

package main

import "fmt"

func main() {
	//int int
	//var int int = 3
	// var 5x int = 100
	// var !i = 100
	var 你好 int = 100
	fmt.Println(你好)
	var abcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyz int = 10
	fmt.Println(abcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyzabcdedghijklmnopqestuvwxyz)

	//fmt.Println(int)
}
